version: '3.8'

services:
  postgres:
    image: postgres:15
    networks:
      - postgres
    ports:
      - "5432:5432"
    volumes:
      - wb-service:/var/lib/postgresql/data
    env_file: 
      - .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_HOST_AUTH_METHOD=trust

  app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
    wb-service:

networks:
    postgres: